@host=https://localhost:7138
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTgzMjIxNy0wZWQ5LTQ0OWEtYTMzYS02MzNlYTNjYmRiOTIiLCJnaXZlbl9uYW1lIjoiVXJtYXQiLCJmYW1pbHlfbmFtZSI6IkVya2ltYmFldiIsImp0aSI6IjI2M2NhYmFkLThmNGUtNGM0MS1iZTI5LTZhMWZlMDZhMWJlYiIsImV4cCI6MTczODI0MDc1NiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.JvaLzKkqSVXXx0Pkb7s_Cwotf6YkGE8ktXSQTuM_GEE