@host=https://localhost:7138
GET {{host}}/dinners
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MGJkYTA0My1kMmUxLTQxYWMtYTAyNS01MTczNjUyMzE4OTIiLCJnaXZlbl9uYW1lIjoiVXJtYXQiLCJmYW1pbHlfbmFtZSI6IkVya2ltYmFldiIsImp0aSI6IjgzYmRkZmQzLTczZWYtNDYxZi04ZGMxLTQ3NWJlMjMzNWM3NyIsImV4cCI6MTczODI0MDQ2NCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.RXcDCpqGtiNVaNREYt61-jHrWH9utQBikA9-JVRub70