@host=https://localhost:7138

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Urmat",
    "lastName": "Erkimbaev",
    "email":"ahiless82@gmail.com",
    "password": "Urmat123!"
}