@host=https://localhost:7138
@hostId=ada
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uRW50aXRpZXMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJVcm1hdCIsImZhbWlseV9uYW1lIjoiRXJraW1iYWV2IiwianRpIjoiY2UwNjYxNDktMjYwNS00YzFlLTkwMjMtNzg5YTUxZjljMmY1IiwiZXhwIjoxNzM5MTk4MzkxLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.RU4XPmJe0eCizo9GV-Uu20Xl765ejJonNKgpUBt7IOI
POST  {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Yummy Menu",
    "description": "A menu with yummy",
    "averageRating":5
    "sections":[
        {
            "name": "Appet",
            "description": "Description Appet",
            "items":[
                {
                    "name": "fried Pickles",
                    "description": "Description fried"
                }
            ]
        }
    ]
}